name: Backup Git

on: [push, delete]

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # <-- must use actions/checkout fetch-depth = 0 before mirroring!
        with:
          fetch-depth: 0

      - uses: PopcornPalace/git-mirroring-action@main
        with:
          target_repo_url: ${{ secrets.CODECOMMIT_TARGET_REPO }}
          ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
